import androidx.compose.ui.unit.dp

val SURFACE_ELEVATION_DP = 20.dp
val CARD_ELEVATION_DP = 10.dp
val BOTTOM_SHEET_PADDING = 20.dp
val CARD_OUTER_PADDING = 10.dp
val CARD_INNER_PADDING = 10.dp
val SEARCH_BAR_PADDING = 10.dp
val SEARCH_BAR_ERROR_MSG_START_PADDING = 20.dp
val BOTTOM_SHEET_PEEK_HEIGHT = 0.dp
val BOTTOM_SHEET_CORNER_RADIUS = 16.dp
val AIRPLANE_ICON_PADDING = 20.dp
